<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClCompile Include="src\base\Client\CCookieClient.cpp" />
    <ClCompile Include="src\base\Client\Features\Cookie\Bhop.cpp" />
    <ClCompile Include="src\base\Client\Features\Cookie\ThirdPerson.cpp" />
    <ClCompile Include="src\base\Client\Game\Trace.cpp" />
    <ClCompile Include="src\base\Client\CCookieGUI.cpp" />
    <ClCompile Include="src\base\Client\Fonts\CFont.cpp" />
    <ClCompile Include="src\base\Client\Fonts\CFontManager.cpp" />
    <ClCompile Include="src\base\Client\Render\CRender.cpp" />
    <ClCompile Include="src\base\Client\Render\CRenderStackSystem.cpp" />
    <ClCompile Include="src\base\Client\Settings\CSettingsJson.cpp" />
    <ClCompile Include="src\base\Common\CrashLog.cpp" />
    <ClCompile Include="src\base\Common\DevLog.cpp" />
    <ClCompile Include="src\base\Common\Helpers\ModuleLoaderHelper.cpp" />
    <ClCompile Include="src\base\Common\Helpers\StringHelper.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui_draw.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui_impl_dx11.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui_impl_win32.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui_tables.cpp" />
    <ClCompile Include="src\base\Common\Include\ImGui\imgui_widgets.cpp" />
    <ClCompile Include="src\base\Common\MemoryEngine.cpp" />
    <ClCompile Include="src\base\CS2\CBasePattern.cpp" />
    <ClCompile Include="src\base\CS2\CHook_Loader.cpp" />
    <ClCompile Include="src\base\CS2\CSDK_Loader.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_OverrideView.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_AllowCameraChange.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_AntiTamper.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_CreateMove.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_CreateSwapChain.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_DrawGlow.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_EquipItemInLoadout.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_FireEventClientSide.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_FrameStageNotify.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_GetMatricesForView.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_IsLoadoutAllowed.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_IsRelativeMouseMode.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_MouseInputEnabled.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_OnAddEntity.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_OnClientOutput.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_OnRemoveEntity.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_ParseMessage.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_Present.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_ResizeBuffers.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_SOCacheSubscribed.cpp" />
    <ClCompile Include="src\base\CS2\Hook\Hook_UpdateInPVS.cpp" />
    <ClCompile Include="src\base\CS2\Protobuf\base_gcmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\clientmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\connectionless_netmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\cstrike15_gcmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\cstrike15_usermessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\cs_gameevents.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\cs_prediction_events.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\cs_usercmd.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\c_peer2peer_netmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\demo.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\econ_gcmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\engine_gcmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\enums_clientserver.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\fatdemo.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\gameevents.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\gcsdk_gcmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\gcsystemmsgs.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\netmessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\networkbasetypes.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\networksystem_protomessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\network_connection.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\prediction_events.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\source2_steam_stats.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steamdatagram_messages_auth.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steamdatagram_messages_sdr.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_cloud.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_gamenetworkingui.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_helprequest.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_oauth.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_player.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_publishedfile.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steammessages_unified_base.steamworkssdk.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steamnetworkingsockets_messages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steamnetworkingsockets_messages_certs.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\steamnetworkingsockets_messages_udp.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\te.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\uifontfile_format.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\usercmd.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\usermessages.pb.cc" />
    <ClCompile Include="src\base\CS2\Protobuf\valveextensions.pb.cc" />
    <ClCompile Include="src\base\CS2\SDK\CFunctionList.cpp" />
    <ClCompile Include="src\base\CS2\SDK\CSchemaOffset.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Cstrike15\CCSInventoryManager.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Cstrike15\CCSPlayerInventory.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Econ\CEconItem.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Econ\CEconItemDefinition.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Econ\CEconItemSchema.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Econ\CEconItemSystem.cpp" />
    <ClCompile Include="src\base\CS2\SDK\GCSDK\CGCClientSharedObjectCache.cpp" />
    <ClCompile Include="src\base\CS2\SDK\GCSDK\CGCClientSharedObjectTypeCache.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Interface\IGameEvent.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Interface\Interface.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Math\Math.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Math\Matrix.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Math\QAngle.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Math\Vector3.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Math\Vector4.cpp" />
    <ClCompile Include="src\base\CS2\SDK\SDK.cpp" />
    <ClCompile Include="src\base\CS2\SDK\SDL3\SDL3_Functions.cpp" />
    <ClCompile Include="src\base\CS2\SDK\TIER0\TIER0_Functions.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Types\CEntityData.cpp" />
    <ClCompile Include="src\base\CS2\SDK\Types\CHandle.cpp" />
    <ClCompile Include="src\base\DllLauncher.cpp" />
    <ClCompile Include="src\base\DllMain.cpp" />
    <ClCompile Include="src\base\GameClient\CEntityCache\CEntityCache.cpp" />
    <ClCompile Include="src\base\GameClient\CL_Bones.cpp" />
    <ClCompile Include="src\base\GameClient\CL_Bypass.cpp" />
    <ClCompile Include="src\base\GameClient\CL_ItemDefinition.cpp" />
    <ClCompile Include="src\base\GameClient\CL_Players.cpp" />
    <ClCompile Include="src\base\GameClient\CL_Trace.cpp" />
    <ClCompile Include="src\base\GameClient\CL_VisibleCheck.cpp" />
    <ClCompile Include="src\base\GameClient\CL_Weapons.cpp" />
  </ItemGroup>
</Project>
