#pragma once

// Single source of truth — bump only COOKIE_VER_MAJOR / COOKIE_VER_MINOR.
#define COOKIE_VER_MAJOR 3
#define COOKIE_VER_MINOR 4

#define COOKIE_VER_STR_HELPER(x) #x
#define COOKIE_VER_STR(x) COOKIE_VER_STR_HELPER(x)
#define COOKIE_VER_STRING COOKIE_VER_STR(COOKIE_VER_MAJOR) "." COOKIE_VER_STR(COOKIE_VER_MINOR)
#define COOKIE_VER_LABEL "v" COOKIE_VER_STRING
